name: crossdevice
description: "Cross-device video/image display"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  change_app_package_name: ^1.3.0

  #Firebase
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_auth: ^5.3.1


  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  mime: ^1.0.5
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  socket_io_client: ^3.0.0
  video_player: ^2.9.1
  http: ^1.2.2
  network_info_plus: ^6.0.1
  web_socket_channel: ^3.0.1
  multicast_dns: ^0.3.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  image: ^4.2.0
  vector_math: ^2.1.4
  flutter_speed_dial: ^7.0.0
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/auth/logo_login.png