name: crossdevice
description: "Cross-device video/image display"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  change_app_package_name: ^1.3.0

  #Firebase
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0


  flutter:
    sdk: flutter
  flutter_mdns_plugin: ^0.0.3
  image_picker: ^1.1.2
  mime: ^1.0.5
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  socket_io_client: ^2.0.3+1
  video_player: ^2.9.1
  http: ^1.2.2
  network_info_plus: ^6.0.1
  web_socket_channel: ^3.0.1
  multicast_dns: ^0.3.2+7
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  image: ^4.2.0
  vector_math: ^2.1.4
  flutter_speed_dial: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
