// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcs7gQm41t8ioIVlvNon3NjX1srksREi8',
    appId: '1:666842905967:web:7eca25f41de90a02563c9a',
    messagingSenderId: '666842905967',
    projectId: 'cross-device-d3fef',
    authDomain: 'cross-device-d3fef.firebaseapp.com',
    storageBucket: 'cross-device-d3fef.appspot.com',
    measurementId: 'G-19GPVT360Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcn-uBpoSFiE0KgN3A9TyEcMqBgV_o5U',
    appId: '1:666842905967:android:272bb93ffa033d1b563c9a',
    messagingSenderId: '666842905967',
    projectId: 'cross-device-d3fef',
    storageBucket: 'cross-device-d3fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8MuDXAx3zL4fpOIzEdMa_cgIC3rJhtV4',
    appId: '1:666842905967:ios:67ac600ec23f166e563c9a',
    messagingSenderId: '666842905967',
    projectId: 'cross-device-d3fef',
    storageBucket: 'cross-device-d3fef.appspot.com',
    iosBundleId: 'com.huayhuajefferson.cross-device-display',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8MuDXAx3zL4fpOIzEdMa_cgIC3rJhtV4',
    appId: '1:666842905967:ios:070bd14067a400c0563c9a',
    messagingSenderId: '666842905967',
    projectId: 'cross-device-d3fef',
    storageBucket: 'cross-device-d3fef.appspot.com',
    iosBundleId: 'com.example.crossdevice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcs7gQm41t8ioIVlvNon3NjX1srksREi8',
    appId: '1:666842905967:web:4d078cfcef2bafa5563c9a',
    messagingSenderId: '666842905967',
    projectId: 'cross-device-d3fef',
    authDomain: 'cross-device-d3fef.firebaseapp.com',
    storageBucket: 'cross-device-d3fef.appspot.com',
    measurementId: 'G-BWBLG4LJCP',
  );
}
